spring:
  application:
    name: billing-job

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USER}
    password: ${DB_PASS}

  batch:
    jdbc:
      initialize-schema: "always"
